/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myapp;

public class App {

  public static void main(String[] args) {
    System.out.println("나의 출결 관리 시스템");
    System.out.println("=================================");

    System.out.println("날짜: ");
    System.out.println("2023-06-06");

    System.out.printf("이름: %s", "홍길도");
    System.out.println();

    System.out.printf("입실 시간: %s", "09:12");
    System.out.println();

    System.out.printf("퇴실 시간: %s", "18:12");
    System.out.println();

    System.out.printf("스터디 시간: %s", "21:00");

  }
}
