/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myapp;

import java.time.LocalDate;

public class App {

  public static void main(String[] args) {
    System.out.println("나의 출결 관리 시스템");
    System.out.println("=================================");

    LocalDate date = LocalDate.now();
    String studentName = "홍길동";
    String entryTime = "09:12";
    String exitTime = "18:12";
    String studyTime = "21:00";

    System.out.printf("날짜: %s\n", date.toString());
    System.out.printf("이름: %s\n", studentName);
    System.out.printf("입실 시간: %s\n", entryTime);
    System.out.printf("퇴실 시간: %s\n", exitTime);
    System.out.printf("스터디 시간: %s", studyTime);

  }
}
